# Generated by Django 2.2.6 on 2019-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
